services:
  intranet:
    build: .
    container_name: admin-server
    env_file:
      - .env

    networks:
      ott-net:
        ipv4_address: 172.16.0.3

    ports:
      - "8001:80"

    restart: unless-stopped

networks:
  ott-net:
    name: ott-net
    external: true
